// Copyright (c) 2025, the Dart project authors.  Please see the AUTHORS file
// for details. All rights reserved. Use of this source code is governed by a
// BSD-style license that can be found in the LICENSE file.

/// @assertion A declaring constructor declaration is a declaration that
/// contains a `<declaringConstructorSignature>` with a
/// `<declaringParameterList>`, or a declaration that contains a
/// `<declaringConstantConstructorSignature>`, or it is a
/// `<primaryConstructorNoConst>` in the header of a class, enum, or extension
/// type declaration, together with a declaration in the body that contains a
/// `<declaringConstructorSignature>`.
///
/// @description Check that members initialized in primary initializer scope can
/// be debugged.
/// @author sgrekhov22@gmail.com

// SharedOptions=--enable-experiment=primary-constructors

import 'dart:developer';
import 'package:vm_service/vm_service.dart';

import '../../../../pkg/vm_service/test/common/service_test_common.dart';
import '../../../../pkg/vm_service/test/common/test_helper.dart';
import '../Utils/expect.dart';

const String shortFile = 'primary_constructors_t02.dart';

// AUTOGENERATED START
//
// Update these constants by running:
//
// dart pkg/vm_service/test/update_line_numbers.dart tests/co19/src/VM/primary_constructors_t02.dart
//
const LINE_A = 39;
const LINE_B = 42;
const LINE_C = 43;
// AUTOGENERATED END

class C1(var String x);   // LINE_A

void testeeMain() {
  debugger();             // LINE_B
  C1("xxx");              // LINE_C
}

final tests = <IsolateTest>[
  hasStoppedAtBreakpoint,
  stoppedAtLine(LINE_B),
  stepInto,
  stoppedAtLine(LINE_C),
  stepInto,
  stoppedAtLine(LINE_A),
  (VmService service, IsolateRef isolateRef) async {
    final isolateId = isolateRef.id!;
    final xRef1 =
        await service.evaluateInFrame(isolateId, 0, 'x') as InstanceRef;
    Expect.equals("null", xRef1.valueAsString);
    final xRef2 =
        await service.evaluateInFrame(isolateId, 0, 'this.x') as InstanceRef;
    Expect.equals("null", xRef2.valueAsString);
  },
  stepInto,
  (VmService service, IsolateRef isolateRef) async {
    final isolateId = isolateRef.id!;
    final xRef1 =
        await service.evaluateInFrame(isolateId, 0, 'x') as InstanceRef;
    Expect.equals('xxx', xRef1.valueAsString);
    final xRef2 =
        await service.evaluateInFrame(isolateId, 0, 'this.x') as InstanceRef;
    Expect.equals('xxx', xRef2.valueAsString);
  },
];

void main([args = const <String>[]]) => runIsolateTests(
  args,
  tests,
  'primary_constructors_t02.dart',
  pauseOnExit: true,
  testeeConcurrent: testeeMain,
);
