// Copyright (c) 2026, the Dart project authors.  Please see the AUTHORS file
// for details. All rights reserved. Use of this source code is governed by a
// BSD-style license that can be found in the LICENSE file.

/// @assertion A primary constructor declaration consists of a
/// `<primaryConstructor>` in the declaration header plus optionally a member
/// declaration in the body that starts with a
/// `<primaryConstructorBodySignature>`.
///
/// @description Check that in-body part of a primary constructor can be
/// debugged. Test extension types.
/// @author sgrekhov22@gmail.com
/// @issue 62053

// SharedOptions=--enable-experiment=primary-constructors

import 'dart:developer';
import 'package:vm_service/vm_service.dart';

import '../../../../pkg/vm_service/test/common/service_test_common.dart';
import '../../../../pkg/vm_service/test/common/test_helper.dart';
import '../Utils/expect.dart';

const String shortFile = 'primary_constructors_t05.dart';

// AUTOGENERATED START
//
// Update these constants by running:
//
// dart pkg/vm_service/test/update_line_numbers.dart tests/co19/src/VM/primary_constructors_t05.dart
//
const LINE_A = 51;
const LINE_B = 52;
const LINE_C = 55;
const LINE_D = 57;
const LINE_E = 58;
const LINE_F = 61;
const LINE_G = 62;
const LINE_H = 63;
const LINE_I = 64;
const LINE_J = 68;
const LINE_K = 69;
const LINE_L = 70;
const LINE_M = 71;
const LINE_N = 72;
// AUTOGENERATED END

final int x = 42;
int y = 0;

extension type ET1(int x) {   // LINE_A
  this : assert(x > 0);       // LINE_B
}

extension type ET2(int x) {   // LINE_C
  this {
   y = 2;                     // LINE_D
  }                           // LINE_E
}

extension type ET3(int x) {   // LINE_F
  this : assert(x > 0) {      // LINE_G
    y = 3;                    // LINE_H
  }                           // LINE_I
}

void testeeMain() {
  debugger();             // LINE_J
  ET1(1);                 // LINE_K
  ET2(2);                 // LINE_L
  ET3(3);                 // LINE_M
}                         // LINE_N

final tests = <IsolateTest>[
  hasStoppedAtBreakpoint,
  stoppedAtLine(LINE_J),
  stepInto,
  stoppedAtLine(LINE_K),
  stepInto,
  stoppedAtLine(LINE_A),
  (VmService service, IsolateRef isolateRef) async {
    final islId = isolateRef.id!;
    final xRef1 = await service.evaluateInFrame(islId, 0, 'x') as InstanceRef;
    Expect.equals('42', xRef1.valueAsString);
  },
  stepInto,
  stoppedAtLine(LINE_B),
  (VmService service, IsolateRef isolateRef) async {
    final islId = isolateRef.id!;
    final xRef1 = await service.evaluateInFrame(islId, 0, 'x') as InstanceRef;
    Expect.equals('1', xRef1.valueAsString);
  },
  stepInto,
  stoppedAtLine(LINE_L),
  stepInto,
  stoppedAtLine(LINE_C),
  (VmService service, IsolateRef isolateRef) async {
    final islId = isolateRef.id!;
    final xRef1 = await service.evaluateInFrame(islId, 0, 'x') as InstanceRef;
    Expect.equals('42', xRef1.valueAsString);
  },
  stepInto,
  stoppedAtLine(LINE_D),
  (VmService service, IsolateRef isolateRef) async {
    final islId = isolateRef.id!;
    final xRef1 = await service.evaluateInFrame(islId, 0, 'x') as InstanceRef;
    Expect.equals('2', xRef1.valueAsString);
    final xRef12= await service.evaluateInFrame(islId, 0, 'y') as InstanceRef;
    Expect.equals('0', xRef1.valueAsString);
  },
  stepInto,
  stoppedAtLine(LINE_E),
  (VmService service, IsolateRef isolateRef) async {
    final islId = isolateRef.id!;
    final xRef1 = await service.evaluateInFrame(islId, 0, 'x') as InstanceRef;
    Expect.equals('2', xRef1.valueAsString);
    final xRef2 = await service.evaluateInFrame(islId, 0, 'y') as InstanceRef;
    Expect.equals('2', xRef2.valueAsString);
  },
  stepInto,
  stoppedAtLine(LINE_M),
  stepInto,
  stoppedAtLine(LINE_F),
  (VmService service, IsolateRef isolateRef) async {
    final islId = isolateRef.id!;
    final xRef1 = await service.evaluateInFrame(islId, 0, 'x') as InstanceRef;
    Expect.equals('42', xRef1.valueAsString);
    final xRef2 = await service.evaluateInFrame(islId, 0, 'y') as InstanceRef;
    Expect.equals('2', xRef2.valueAsString);
  },
  stepInto,
  stoppedAtLine(LINE_G),
  (VmService service, IsolateRef isolateRef) async {
    final islId = isolateRef.id!;
    final xRef1 = await service.evaluateInFrame(islId, 0, 'x') as InstanceRef;
    Expect.equals('2', xRef1.valueAsString);
    final xRef2 = await service.evaluateInFrame(islId, 0, 'y') as InstanceRef;
    Expect.equals('2', xRef2.valueAsString);
  },
  stepInto,
  stoppedAtLine(LINE_H),
  (VmService service, IsolateRef isolateRef) async {
    final islId = isolateRef.id!;
    final xRef1 = await service.evaluateInFrame(islId, 0, 'x') as InstanceRef;
    Expect.equals('3', xRef1.valueAsString);
    final xRef2 = await service.evaluateInFrame(islId, 0, 'y') as InstanceRef;
    Expect.equals('2', xRef2.valueAsString);
  },
  stepInto,
  stoppedAtLine(LINE_I),
      (VmService service, IsolateRef isolateRef) async {
    final islId = isolateRef.id!;
    final xRef1 = await service.evaluateInFrame(islId, 0, 'x') as InstanceRef;
    Expect.equals('3', xRef1.valueAsString);
    final xRef2 = await service.evaluateInFrame(islId, 0, 'y') as InstanceRef;
    Expect.equals('3', xRef2.valueAsString);
  },
  stepInto,
  stoppedAtLine(LINE_N),
];

void main([args = const <String>[]]) => runIsolateTests(
  args,
  tests,
  'primary_constructors_t05.dart',
  pauseOnExit: true,
  testeeConcurrent: testeeMain,
);
