// Copyright (c) 2026, the Dart project authors.  Please see the AUTHORS file
// for details. All rights reserved. Use of this source code is governed by a
// BSD-style license that can be found in the LICENSE file.

/// @assertion A primary constructor declaration consists of a
/// `<primaryConstructor>` in the declaration header plus optionally a member
/// declaration in the body that starts with a
/// `<primaryConstructorBodySignature>`.
///
/// @description Check that breakpoint can be set on a primary constructor. Test
/// extension types.
/// @author sgrekhov22@gmail.com
/// @issue 62053

// SharedOptions=--enable-experiment=primary-constructors

import 'dart:developer';
import 'package:vm_service/vm_service.dart';

import '../../../../pkg/vm_service/test/common/service_test_common.dart';
import '../../../../pkg/vm_service/test/common/test_helper.dart';
import '../Utils/expect.dart';

const String shortFile = 'primary_constructors_t06.dart';

// AUTOGENERATED START
//
// Update these constants by running:
//
// dart pkg/vm_service/test/update_line_numbers.dart tests/co19/src/VM/primary_constructors_t06.dart
//
const LINE_A = 37;
const LINE_B = 42;
// AUTOGENERATED END

extension type ET1(int v) {
  this: assert(v > 0);          // LINE_A
}

extension type ET2(int v) {
  this {
    print(v);                   // LINE_B
  }
}

void testeeMain() {
  debugger();
  ET1(1);
  ET2(2);
}

final tests = <IsolateTest>[
  hasStoppedAtBreakpoint,

  // Test interaction of breakpoints with primary constructors.
  (VmService service, IsolateRef isolateRef) async {
    final isolateId = isolateRef.id!;
    final isolate = await service.getIsolate(isolateId);
    final lib =
        (await service.getObject(isolateId, isolate.rootLib!.id!)) as Library;
    final scriptId = lib.scripts!.first.id!;

    var breakpoint = await service.addBreakpoint(isolateId, scriptId, LINE_A);
    var (_, (line, column)) = await breakpoint.getLocation(service, isolateRef);
    Expect.isTrue(breakpoint.enabled);
    Expect.equals(LINE_A, line);
    Expect.equals(9, column); // on 'assert'

    breakpoint = await service.addBreakpoint(isolateId, scriptId, LINE_B);
    (_, (line, column)) = await breakpoint.getLocation(service, isolateRef);
    Expect.isTrue(breakpoint.enabled);
    Expect.equals(LINE_B, line);
    Expect.equals(44, column); // on 'print'

    await service.removeBreakpoint(isolateId, breakpoint.id!);
  },
];

void main([args = const <String>[]]) => runIsolateTests(
  args,
  tests,
  'primary_constructors_t06.dart',
  pauseOnExit: true,
  testeeConcurrent: testeeMain,
);
