// Copyright (c) 2026, the Dart project authors.  Please see the AUTHORS file
// for details. All rights reserved. Use of this source code is governed by a
// BSD-style license that can be found in the LICENSE file.

/// @assertion A primary constructor declaration consists of a
/// `<primaryConstructor>` in the declaration header plus optionally a member
/// declaration in the body that starts with a
/// `<primaryConstructorBodySignature>`.
///
/// @description Check that in-body part of a primary initializer scope can be
/// debugged.
/// @author sgrekhov22@gmail.com
/// @issue 62053

// SharedOptions=--enable-experiment=primary-constructors

import 'dart:developer';
import 'package:vm_service/vm_service.dart';

import '../../../../pkg/vm_service/test/common/service_test_common.dart';
import '../../../../pkg/vm_service/test/common/test_helper.dart';
import '../Utils/expect.dart';

const String shortFile = 'primary_constructors_t03.dart';

// AUTOGENERATED START
//
// Update these constants by running:
//
// dart pkg/vm_service/test/update_line_numbers.dart tests/co19/src/VM/primary_constructors_t03.dart
//
const LINE_A = 48;
const LINE_B = 50;
const LINE_C = 53;
const LINE_D = 56;
const LINE_E = 60;
const LINE_F = 64;
const LINE_G = 69;
const LINE_H = 70;
const LINE_I = 71;
const LINE_J = 72;
// AUTOGENERATED END

final int x = 42;
final String y = '42';
const String z = '42';

class C1(var String x) {    // LINE_A
  String y;
  this : y = 'yyy';         // LINE_B
}

class C2(var String x) {    // LINE_C
  String? y;
  this {
    y = 'yyy';              // LINE_D
  }
}

class C3(var String x) {    // LINE_E
  String y;
  String? z;
  this : y = x {
    z = 'zzz';              // LINE_F
  }
}

void testeeMain() {
  debugger();             // LINE_G
  C1('xxx');              // LINE_H
  C2('xxx');              // LINE_I
  C3('xxx');              // LINE_J
}

final tests = <IsolateTest>[
  hasStoppedAtBreakpoint,
  stoppedAtLine(LINE_G),
  stepInto,
  stoppedAtLine(LINE_H),
  stepInto,
  stoppedAtLine(LINE_A),
  (VmService service, IsolateRef isolateRef) async {
    final islId = isolateRef.id!;
    final xRef1 = await service.evaluateInFrame(islId, 0, 'x') as InstanceRef;
    Expect.equals('null', xRef1.valueAsString);
    final xRef2 = await service.evaluateInFrame(islId, 0, 'y') as InstanceRef;
    Expect.equals('null', xRef2.valueAsString);
  },
  stepInto,
  (VmService service, IsolateRef isolateRef) async {
    final islId = isolateRef.id!;
    final xRef1 = await service.evaluateInFrame(islId, 0, 'x') as InstanceRef;
    Expect.equals('xxx', xRef1.valueAsString);
    final xRef2 = await service.evaluateInFrame(islId, 0, 'y') as InstanceRef;
    Expect.equals('yyy', xRef2.valueAsString);
  },
  stepInto,
  stoppedAtLine(LINE_I),
  stepInto,
  stoppedAtLine(LINE_C),
  (VmService service, IsolateRef isolateRef) async {
    final islId = isolateRef.id!;
    final xRef1 = await service.evaluateInFrame(islId, 0, 'x') as InstanceRef;
    Expect.equals('null', xRef1.valueAsString);
    final xRef2 = await service.evaluateInFrame(islId, 0, 'y') as InstanceRef;
    Expect.equals('null', xRef2.valueAsString);
  },
  stepInto,
  stoppedAtLine(LINE_D),
  (VmService service, IsolateRef isolateRef) async {
    final islId = isolateRef.id!;
    final xRef1 = await service.evaluateInFrame(islId, 0, 'x') as InstanceRef;
    Expect.equals('xxx', xRef1.valueAsString);
    final xRef2 = await service.evaluateInFrame(islId, 0, 'y') as InstanceRef;
    Expect.equals('null', xRef2.valueAsString);
  },
  stepInto,
  stoppedAtLine(LINE_D),
  (VmService service, IsolateRef isolateRef) async {
    final islId = isolateRef.id!;
    final xRef1 = await service.evaluateInFrame(islId, 0, 'x') as InstanceRef;
    Expect.equals('xxx', xRef1.valueAsString);
    final xRef2 = await service.evaluateInFrame(islId, 0, 'y') as InstanceRef;
    Expect.equals('yyy', xRef2.valueAsString);
  },
  stepInto,
  stoppedAtLine(LINE_J),
  stepInto,
  stoppedAtLine(LINE_E),
  (VmService service, IsolateRef isolateRef) async {
    final islId = isolateRef.id!;
    final xRef1 = await service.evaluateInFrame(islId, 0, 'x') as InstanceRef;
    Expect.equals('null', xRef1.valueAsString);
    final xRef2 = await service.evaluateInFrame(islId, 0, 'y') as InstanceRef;
    Expect.equals('null', xRef2.valueAsString);
    final xRef3 = await service.evaluateInFrame(islId, 0, 'z') as InstanceRef;
    Expect.equals('null', xRef3.valueAsString);
  },
  stepInto,
  stoppedAtLine(LINE_F),
  (VmService service, IsolateRef isolateRef) async {
    final islId = isolateRef.id!;
    final xRef1 = await service.evaluateInFrame(islId, 0, 'x') as InstanceRef;
    Expect.equals('xxx', xRef1.valueAsString);
    final xRef2 = await service.evaluateInFrame(islId, 0, 'y') as InstanceRef;
    Expect.equals('xxx', xRef2.valueAsString);
    final xRef3 = await service.evaluateInFrame(islId, 0, 'z') as InstanceRef;
    Expect.equals('null', xRef3.valueAsString);
  },
  stepInto,
  stoppedAtLine(LINE_F),
  (VmService service, IsolateRef isolateRef) async {
    final islId = isolateRef.id!;
    final xRef1 = await service.evaluateInFrame(islId, 0, 'x') as InstanceRef;
    Expect.equals('xxx', xRef1.valueAsString);
    final xRef2 = await service.evaluateInFrame(islId, 0, 'y') as InstanceRef;
    Expect.equals('xxx', xRef2.valueAsString);
    final xRef3 = await service.evaluateInFrame(islId, 0, 'z') as InstanceRef;
    Expect.equals('zzz', xRef3.valueAsString);
  },
];

void main([args = const <String>[]]) => runIsolateTests(
  args,
  tests,
  'primary_constructors_t03.dart',
  pauseOnExit: true,
  testeeConcurrent: testeeMain,
);
