#!/bin/sh
pref1=".dart"
pref2=".test.dart"
#echo "ls ${pref1}*"

for file in `ls *${pref1}`
do
  tail=`expr match "$file" '.*\([0-9].dart\)'`
  if [ ${#tail} -gt 0 ];
  then
    newname=${file%$pref1}${pref2}
    echo mv $file ${newname}
  fi
done

