./rs.sh BadNumberFormatException
./rs.sh ClosureArgumentMismatchException
./rs.sh EmptyQueueException
./rs.sh Exception
./rs.sh ExpectException
./rs.sh IllegalAccessException
./rs.sh IllegalArgumentException
./rs.sh IllegalJSRegExpException
./rs.sh IndexOutOfRangeException
./rs.sh IntegerDivisionByZeroException
./rs.sh NoMoreElementsException
./rs.sh NoSuchMethodException
./rs.sh NotImplementedException
./rs.sh NullPointerException
./rs.sh ObjectNotClosureException
./rs.sh OutOfMemoryException
./rs.sh StackOverflowException
./rs.sh UnsupportedOperationException
./rs.sh WrongArgumentCountException
