name: co19_unquoted_imports
description: co19 tests for Unquoted imports feature

# This tests isn't intended for publishing on pub.dev.
publish_to: none

environment:
  sdk: '>=3.6.0-255.0.dev'

dependencies:
  test.package1:
    path: ./test.package1
  test_package2:
    path: ./test_package2
  test.package1.dart:
    path: ./test.package1.dart
