name: co19_ffi
description: co19 tests for Dart FFI library

# This tests isn't intended for publishing on pub.dev.
publish_to: none

environment:
  sdk: '>=3.3.0-279.1.beta <4.0.0'

dependencies:
  ffi: ^2.1.0
